FROM ubuntu:18.04

# Here is QualiMap's installation documentation needs: http://qualimap.bioinfo.cipf.es/doc_html/intro.html#installation
# 1. JAVA runtime > 6
# 2. R enviroment > 3.1
# 3. R Packages: optparse (CRAN), NOISeq (Bioconductor), Repitools (Bioconductor), Rsamtools (Bioconductor), GenomicFeatures (Bioconductor), rtracklayer (Bioconductor) 


RUN mkdir -p /data
RUN mkdir -p /opt

# Using apt-get to install wget
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y r-base-core libboost-dev
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
	openjdk-8-jre \
	locales \
	libssl-dev \
	libcurl4-openssl-dev \
	g++ \
	gcc \
	wget \	
	libxml2-dev \
	openssl \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* 

WORKDIR /opt

# Download QualiMap, unzip resources, and rename executable 
COPY qualimap_v2.2.1.zip /opt
RUN unzip qualimap_v2.2.1.zip \
  && rm qualimap_v2.2.1.zip \
  && mv /opt/qualimap_v2.2.1 /opt/qualimap

# Adding QualiMap to $PATH
ENV PATH=$PATH:/opt/qualimap

# Setting language environment variable
ENV LANG en_US.UTF-8 

# Install R packages 
COPY install_dependencies.r /opt
RUN Rscript /opt/install_dependencies.r

COPY Dockerfile /opt

WORKDIR /data
